// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhNYFpTkKv_ZblZFNzqBZQuO3o2JGcHBU',
    appId: '1:192297844009:web:be13c2b1f8aeaa8a938b38',
    messagingSenderId: '192297844009',
    projectId: 'daamduuqr',
    authDomain: 'daamduuqr.firebaseapp.com',
    storageBucket: 'daamduuqr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5BSfOCu_FsVddtmUXnjbbbPwGVScuHXI',
    appId: '1:192297844009:android:78a67769e24b7456938b38',
    messagingSenderId: '192297844009',
    projectId: 'daamduuqr',
    storageBucket: 'daamduuqr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeeUTrlyf4RnLDmTBpBjgTIzHQSy3ns-c',
    appId: '1:192297844009:ios:344113b8b0d0c2db938b38',
    messagingSenderId: '192297844009',
    projectId: 'daamduuqr',
    storageBucket: 'daamduuqr.firebasestorage.app',
    iosBundleId: 'com.daamduuqr.mobile.app',
  );
}
