platform :ios, '15.0'

use_frameworks!
use_modular_headers!

flutter_application_path = File.expand_path('..', __dir__)
require File.expand_path(File.join(flutter_application_path, 'flutter_export_environment'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Подключение плагинов
  pod 'Flutter', :path => File.join(flutter_application_path, 'Flutter')

  # Включаем нужные разрешения
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'PERMISSION_CAMERA=1',
          'PERMISSION_PHOTOS=1',
          'PERMISSION_LOCATION_WHEN_IN_USE=1',
        ]
      end
    end
  end
end